name: Docker Push

on:
  push:
      tags:
        - '*'
      branches:
        - 'main'

jobs:
  build_push:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/lagrange.onebot
          tags: |
            type=edge
            type=sha,event=branch
            type=ref,event=tag
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8, linux/amd64

